include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o
#obj-y   +=  otm9605a_dsi_vdo_cs.o
#obj-y   +=  HX8394D_TXD_HANNSTAR_IPS_HD.o
obj-y   +=  hx8394d_txd_hannstar_ips_hd.o
